@startuml
skinparam conditionStyle inside
title Алгоритм системы "Холодное сердце" (Управление климатом)

start
:Эльза: создатьБурю();

if (Эмоциональный сбой?) then (да)
    #pink:Активирована снежная буря;
    :Эльза: заморозить замок;
    
    if (Создать Олафа?) then (да)
        :Эльза: создатьОлафа();
    else (нет)
        :Пропустить создание Олафа;
    endif

    partition "Попытка остановить зиму" {
        :Анна: активироватьЛюбовь();
        
        if (Сила любви >= Сила магии?) then (да)
            #lightgreen:Зима остановлена!;
            :Система: растопить зиму;
            :Возврат к лету;
        else (нет)
            #pink:Зима продолжается;
            fork
                :Жители: страдают от холода;
            fork again
                :Система: поддерживает вечную зиму;
            end fork
        endif
    }

else (нет)
    :Система работает нормально (лето);
endif

stop
@enduml